export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#0D0C1F',
  AUTH_BACKGROUND_COLOR: '#FFFFFF',
  STATUS_BAR_STYLE: 'light-content',
  LINKS_COLOR: '#005BEA',
  FB_ICON: '#3B5998',
  GOOGLE_ICON: '#EA4335',
  FORM_INPUT_COLOR: '#0D0C1F',
  SECONDARY_COLOR: '#00D1FF',
  BOTTOM_NAVBAR_COLOR: '#0D0C1F',
  BOTTOM_NAVBAR_INACTIVE_ICON_COLOR: '#FFFFFF',
  BOTTOM_NAVBAR_ACTIVE_ICON_COLOR: '#00D1FF',
};

export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#0D0C1F',
  AUTH_BACKGROUND_COLOR: '#0088FF',
  PRIMARY_TEXT_COLOR: '#FFFFFF',
  STATUS_BAR_STYLE: 'dark-content',
  LINKS_COLOR: '#00D1FF',
  FB_ICON: '#FFFFFF',
  GOOGLE_ICON: '#FFFFFF',
  FORM_INPUT_COLOR: '#FFFFFF',
  SECONDARY_COLOR: '#005BEA',
  BOTTOM_NAVBAR_COLOR: '#FFFFFF',
  BOTTOM_NAVBAR_INACTIVE_ICON_COLOR: '#0D0C1F',
  BOTTOM_NAVBAR_ACTIVE_ICON_COLOR: '#005BEA',
};

//010101 #00d1ff #005bea
