export const FETCHING_INITIAL_USER = 'FETCHING_INITIAL_USER';
export const INITIAL_USER_FETCHED = 'INITIAL_USER_FETCHED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const FETCHING_USER = 'FETCHING_USER';
export const USER_FETCHED = 'USER_FETCHED';

export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_NOT_REGISTERED = 'USER_NOT_REGISTERED';

export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const REGISTERING_NEW_USER = "REGISTERING_NEW_USER";
export const NEW_USER_REGISTERED = "USER_REGISTERED";
