export const FETCHING_INITIAL_USER = 'FETCHING_INITIAL_USER';
export const INITIAL_USER_FETCHED = 'INITIAL_USER_FETCHED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const FETCHING_USER = 'FETCHING_USER';
export const USER_FETCHED = 'USER_FETCHED';

export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_NOT_REGISTERED = 'USER_NOT_REGISTERED';

export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const REGISTERING_NEW_USER = 'REGISTERING_NEW_USER';
export const NEW_USER_REGISTERED = 'NEW_USER_REGISTERED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const ASK_PERMISSIONS_LOCATION = 'ASK_PERMISSIONS_LOCATION';
export const LOADING_LOCATION = 'LOADING_LOCATION';
export const LOCATION_LOADED = 'LOCATION_LOADED';
export const LOADING_ADDRESS = 'LOADING_ADDRESS';
export const ADDRESS_LOADED = 'ADDRESS_LOADED';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const ADDRESS_ERROR = 'ADDRESS_ERROR';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';

export const SWITCH_THEME = 'SWITCH_THEME';

export const FETCHING_ALL_PROVIDERS = 'FETCHING_ALL_PROVIDERS';
export const ALL_PROVIDERS_FETCHED = 'ALL_PROVIDERS_FETCHED';
export const FETCHING_PROVIDER_FAILED = 'FETCHING_PROVIDER_FAILED';
